spring.application.name=reading-material-library

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/reading_library?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=reading_library
spring.datasource.password=reading_library
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway
spring.flyway.enabled=true

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info
spring.http.converters.preferred-json-mapper=jackson2

