CREATE TABLE materials (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           title VARCHAR(255) NOT NULL,

    /*
     * Kept as VARCHAR rather than PostgreSQL ENUM or CHECK constraint.
     *
     * This is intentional:
     * adding a future kind such as VIDEO must not require
     * changing the existing materials table.
     *
     * Application-level validation controls the currently
     * supported kinds.
     */
                           kind VARCHAR(30) NOT NULL,

                           created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT chk_material_title_not_blank
                               CHECK (char_length(trim(title)) > 0)
);