CREATE TABLE material_versions (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   material_id BIGINT NOT NULL,

                                   version_number INTEGER NOT NULL,

                                   status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

                                   created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   published_at TIMESTAMPTZ,

                                   CONSTRAINT fk_material_versions_material
                                       FOREIGN KEY (material_id)
                                           REFERENCES materials(id)
                                           ON DELETE RESTRICT,

                                   CONSTRAINT uq_material_version_number
                                       UNIQUE (material_id, version_number),

                                   CONSTRAINT chk_version_number_positive
                                       CHECK (version_number > 0),

                                   CONSTRAINT chk_material_version_status
                                       CHECK (status IN ('DRAFT', 'LIVE', 'ARCHIVED')),

                                   CONSTRAINT chk_published_at_matches_status
                                       CHECK (
                                           (status = 'DRAFT' AND published_at IS NULL)
                                               OR
                                           (status IN ('LIVE', 'ARCHIVED') AND published_at IS NOT NULL)
                                           )
);