CREATE TABLE reader_progress (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * There is no reader table in the assignment because
     * authentication/user management is deliberately out of scope.
     */
                                 reader_id BIGINT NOT NULL,

                                 material_version_id BIGINT NOT NULL,

    /*
     * Meaning depends on material kind:
     *
     * PDF        -> page number
     * ARTICLE    -> percentage
     * BOOK       -> chapter number
     * SLIDE_DECK -> slide number
     */
                                 position INTEGER NOT NULL,

                                 completed BOOLEAN NOT NULL DEFAULT FALSE,

                                 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_reader_progress_version
                                     FOREIGN KEY (material_version_id)
                                         REFERENCES material_versions(id)
                                         ON DELETE RESTRICT,

                                 CONSTRAINT uq_reader_version_progress
                                     UNIQUE (reader_id, material_version_id),

                                 CONSTRAINT chk_reader_progress_position
                                     CHECK (position >= 0)
);